#--------------------------
# server
#--------------------------
server:
  shutdown: graceful  # graceful shutdown 적용
  servlet:
    encoding:
      charset: utf-8
      force: true


# spring.redis.cluster.mode
#--------------------------
# spring
#--------------------------
spring:
  application:
    name: starter
  profiles:
    active: dev
  lifecycle:
    timeout-per-shutdown-phase: 35s # graceful shutdown 유예시간 설정 (default 30s)

# cache ttl 설정 (cacheName:ttl)
custom:
  cache:

#--------------------------
# logging
#--------------------------
logging.config: classpath:log4j2.xml

#--------------------------
# actuator
#--------------------------
management:
  endpoints:
    enabled-by-default: false # 1. Endpoint all disable
    # 3. Exclude all endpoint for JMX and Expose specific endpoints
    web.exposure.include: "health,info"
    jmx.exposure.exclude: "*"
  # 2. Enable specific endpoints
  endpoint:
    info.enabled: true
    health:
      enabled: true
      probes.enabled: true
      defaults.enabled: true

#--------------------------
# jwt secret
#--------------------------
jwt:
  secret: 1e47d80ac0698f4cf303c6e7ba9a64a07767a21cb3674336489a7d96dee4762ee11e6827a04fa4c172174e88063f085f1d3c9370ead4f3aab44d30b31ea7bd05

#--------------------------
# API CONFIG
#--------------------------
api:
  auth-service: http://localhost:18080